### PR TITLE
Update vcpkg to the latest version in Github CI

### LINKED ISSUE #30: CI integration is failing on Windows
The Windows CI integration is failing with the following error
```
Starting package 2/8: ace:x64-windows
Building package ace[core]:x64-windows...
-- Downloading https://github.com/DOCGroup/ACE_TAO/releases/download/ACE%2BTAO-6_5_8/ACE-src-6.5.8.zip...
-- Extracting source C:/vcpkg/downloads/ACE-src-6.5.8.zip
-- Using source at C:/vcpkg/buildtrees/ace/src/ACE-src-6-a3686a23cb
-- Downloading http://strawberryperl.com/download/5.30.0.1/strawberry-perl-5.30.0.1-32bit.zip...
-- Building C:/vcpkg/buildtrees/ace/src/ACE-src-6-a3686a23cb/ace/ace.sln for Release
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:72 (message):
    Command failed: msbuild C:/vcpkg/buildtrees/ace/src/ACE-src-6-a3686a23cb/ace/ace.sln /p:Configuration=Release /t:Rebuild /p:Platform=x64 /p:PlatformToolset=v142 /p:VCPkgLocalAppDataDisabled=true /p:UseIntelMKL=No /p:WindowsTargetPlatformVersion=10.0.18362.0 /m /p:ForceImportBeforeCppTargets=C:/vcpkg/scripts/buildsystems/msbuild/vcpkg.targets /p:VcpkgTriplet=x64-windows
    Working Directory: C:/vcpkg/buildtrees/ace/x64-windows-rel
    Error code: 1
    See logs for more information:
      C:\vcpkg\buildtrees\ace\build-x64-windows-rel-out.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_build_msbuild.cmake:119 (vcpkg_execute_required_process)
  ports/ace/portfile.cmake:98 (vcpkg_build_msbuild)
```

Running `vcpkg.exe update` should solve the problem

https://github.com/dic-iit/bipedal-locomotion-controllers/runs/527453730

### PR DESCRIPTION
**Pull request by GiulioRomualdi**
This PR fixes #30

### CODE REVIEW

**Comment by traversaro** [comment]
This is quite strange. `vcpkg update` just prints the outdated packages, see https://github.com/Microsoft/vcpkg/blob/master/docs/about/faq.md#how-do-i-update-libraries , it does not modify at all the vcpkg installation.

**Comment by GiulioRomualdi** [comment]
No, It won't fix

**Comment by GiulioRomualdi** [comment]
That's strange.
In  https://github.com/GiulioRomualdi/bipedal-locomotion-controllers/runs/527402672 the code  compiles without any problem but in https://github.com/dic-iit/bipedal-locomotion-controllers/pull/31/checks?check_run_id=527627719 it doesn't compile

**Comment by GiulioRomualdi** [comment]
Closing since it doesn't solve the problem

**Pull request closed without merging**
